# Generated by Django 4.0.4 on 2022-05-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_keagan_best'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keagan_best',
            options={'verbose_name': 'best product', 'verbose_name_plural': 'Best products'},
        ),
        migrations.AlterModelOptions(
            name='keagan_brand',
            options={'verbose_name': 'brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='keagan_product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'Products'},
        ),
    ]
