# Generated by Django 4.0.4 on 2022-06-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_keagan_brand_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keagan_best',
            new_name='KeaganBest',
        ),
        migrations.RenameModel(
            old_name='keagan_brand',
            new_name='KeaganBrand',
        ),
        migrations.RenameModel(
            old_name='keagan_new_product',
            new_name='KeaganNewProduct',
        ),
        migrations.RenameModel(
            old_name='keagan_new_products_categories',
            new_name='KeaganNewProductsCategories',
        ),
        migrations.RenameModel(
            old_name='keagan_product',
            new_name='KeaganProduct',
        ),
    ]
