# Generated by Django 4.0.4 on 2022-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_keaganbrand_image_alter_keagannewproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keaganbrand',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='D:\\Sync\\Dari Developer\\backend\\ecommerce\\storeapi\\store\\static\\store\\imgs_keagan/brands'),
        ),
    ]
