# Generated by Django 4.0.4 on 2022-06-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_keaganbrand_image_alter_keagannewproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keaganbrand',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='keagan/brands'),
        ),
        migrations.AlterField(
            model_name='keagannewproduct',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='keagan/products/full-size'),
        ),
        migrations.AlterField(
            model_name='keaganproduct',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='keagan/products/full-size'),
        ),
    ]
