# Generated by Django 4.0.4 on 2022-05-29 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_keagan_brand_image_alter_keagan_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='keagan_best',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.keagan_product')),
            ],
        ),
    ]
