# Generated by Django 4.0.4 on 2022-06-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_keagan_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keagan_brand',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
