# Generated by Django 4.0.4 on 2022-05-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('details', models.TextField(default=None, max_length=500)),
                ('image', models.ImageField(blank=True, default=None, upload_to='brands')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, default=None, upload_to='products/full-size')),
                ('sizes', models.CharField(max_length=100, verbose_name='Sizes (separted by commas)')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
        ),
    ]
