# Generated by Django 4.0.4 on 2022-05-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='keagansklosetboutique_brand',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='keagansklosetboutique_product',
        ),
    ]
