# Generated by Django 4.0.4 on 2022-05-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_brand_keagansklosetboutique_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keagansklosetboutique_brand',
            new_name='keagan_brand',
        ),
        migrations.RenameModel(
            old_name='keagansklosetboutique_product',
            new_name='keagan_product',
        ),
    ]
