# Generated by Django 4.0.4 on 2022-05-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_keagansklosetboutique_brand_keagan_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keagan_brand',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='imgs/brands'),
        ),
        migrations.AlterField(
            model_name='keagan_product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='imgs/products/full-size'),
        ),
    ]
