# Generated by Django 4.0.4 on 2022-05-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_keagan_new_products_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keagan_new_products_categories',
            name='details',
        ),
    ]
