# Generated by Django 4.0.4 on 2022-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_keagan_new_products_categories_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='keagan_new_products_categories',
            name='details',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
