# Generated by Django 4.0.4 on 2022-06-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_keagannewproductscategories_keagannewproductcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keaganbrand',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='D:\\Sync\\Dari Developer\\backend\\ecommerce\\store\\static\\store\\imgs_keagan/brands'),
        ),
        migrations.AlterField(
            model_name='keagannewproduct',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='D:\\Sync\\Dari Developer\\backend\\ecommerce\\store\\static\\store\\imgs_keagan/products/full-size'),
        ),
        migrations.AlterField(
            model_name='keaganproduct',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='D:\\Sync\\Dari Developer\\backend\\ecommerce\\store\\static\\store\\imgs_keagan/products/full-size'),
        ),
    ]
